# Generated by Django 5.1.6 on 2025-02-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name.', max_length=100)),
                ('last_name', models.CharField(help_text='Enter the last name.', max_length=100)),
                ('email', models.EmailField(help_text='Enter the email address.', max_length=100)),
                ('phone_number', models.CharField(help_text='Enter the phone number.', max_length=100)),
                ('instrument_type', models.CharField(help_text='Enter the instrument type.', max_length=100)),
            ],
        ),
    ]
